### PR TITLE
Add support for reading image data from string

### LINKED ISSUE #147: Feature-request: Read image-data from string instead of from file
With the tesseract-binary you can provide the image from STDIN using the argument "stdin" like this:
```
gerrit@gerrit-macbook:~$ echo '/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wgARCAAMAEADAREAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAgEDAAX/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH1zMAxAKcbiIMBCjP/xAAcEAACAwEBAQEAAAAAAAAAAAABAgADERMSBCP/2gAIAQEAAQUCV/y7Np+nC1zrLbObG9gHv8o1zrOaegirDWhOAx0V5yrnNNwGf//EABQRAQAAAAAAAAAAAAAAAAAAAED/2gAIAQMBAT8BB//EABQRAQAAAAAAAAAAAAAAAAAAAED/2gAIAQIBAT8BB//EACYQAAEDAwIFBQAAAAAAAAAAAAEAAhESISJBUQMxMnGBYWKx0fD/2gAIAQEABj8Cc92hd8oNoFR937ZPwMNm/ZOnhjEVHLRC0+fULo5GDewVUauETtP0nTwxiKjloqqG1bwrNA8KSxs7wjIF1dDBtuVlNDZ7IyBdf//EACEQAQACAgICAgMAAAAAAAAAAAEAESExQVFh0XHBgaHw/9oACAEBAAE/IVM5xOhepzQArTIu6hqD9hsfFcdz2EYeN4ZzmTwNH3GTXItuDkPPUHev4A/j5nsIw8bwwOgvAuV2ObxTMWsLFhcc4KU2bIKB0j+x+iYBj6uIqki20zHOClNmyf/aAAwDAQACAAMAAAAQAggAgAEA/8QAFBEBAAAAAAAAAAAAAAAAAAAAQP/aAAgBAwEBPxAH/8QAFBEBAAAAAAAAAAAAAAAAAAAAQP/aAAgBAgEBPxAH/8QAHhABAQADAQEBAQEBAAAAAAAAAREAITFBUWFxgZH/2gAIAQEAAT8QdB3kFigf4DOtygqRl/opPR3kA35EULXQOg07NZoUhCtvHrxc13NdTcrK7Zz7ryJ645K3OkK0sTpARsxRHwg7l57H8+vdCkIVt49eLmu4/dFUk162Xdf+4EC4QohLr2KX9wG7KSQkSzkZnzCePbT9Nuv1wybAYWEu/FsezFHoihg3s1rmXVjZmhGs3pT+LnzCePbT9Nuv1z//2Q==' | base64 -d | tesseract stdin stdout
Lorem Wm

gerrit@gerrit-macbook:~$
```
(The base64 encoding is probably not even necessary but i cannot paste binary data here on github without it breaking. Also tesseract did not read the "Lorem ipsum" from the small sample-image correctly, but that should not matter for this feature request.)

This way it should not be needed to actually store a file on disk to process the image via tesseract. This can help the usability of this library when dealing with in-memory images (like i am doing right now) because the user does not have to deal with storing files on disk (which can open up a whole new can of failure-points like wrong file-permissions, full ore read-only disk, ...).

Maybe it could even be possible to provide an Imagick object and have the library just read that in-memory image directly using the above method.

What do you think?

### PR DESCRIPTION
**Pull request by LeCodeurDuDimanche**
### Description

Add `imageData()` method which uses an already loaded image as an input 
instead of a file path.
Add `withoutTempFiles()` method which prevent TesseractOCR from creating 
temporary files and use standard output to retrieve the data from 
`tesseract`.

### Related Issues

Resolves  #147
Allows to use images without saving them beforehand.
Improve efficiency by avoiding to write to the file-system.

### CODE REVIEW

**Comment by LeCodeurDuDimanche** [comment]
The tests are now successful (apart from the AppVeyor one, but it is not passing because of a missing package).
Should I submit a new pull request with a cleaner commit history and close this one ?

**Comment by thiagoalessio** [comment]
@LeCodeurDuDimanche awesome! :tada: :balloon: don't worry about AppVeyor, probably that package was renamed, i gotta sort that out.
No need to clean up the commit history, I'll try to set aside some time this weekend to play around with your changes.
Thank you so much for addressing that issue, it was sitting there for almost one year. Let's hope I don't take another year to merge your PR :rofl:
:heart: :green_heart: :yellow_heart: :blue_heart: :purple_heart: :black_heart:

**Comment by LeCodeurDuDimanche** [comment]
Nice ! :smiley:

**Comment by thiagoalessio** [comment]
Your changes are available in version `2.8.0`, thanks for taking the time to contribute!

**Pull request merged**
