### PR TITLE
Added some functionality that we are hoping to use. Improved the DocBlock documentation a little.

### PR DESCRIPTION
**Pull request by drsassafras**
### Description

A brief explanation of what was modified and _why_.

### Related Issues

If this PR was placed to solve one or more issues, just list them here.

### CODE REVIEW

**Comment by drsassafras** [comment]
Looks like the failed tests were a result of conflicts in the CI system. Do you want me to re-submit the commits separately, so they pass the tests? Or is there better ideas about how to get these commits to pass?

**Comment by thiagoalessio** [comment]
Hello @drsassafras !

Thanks a lot for your contribution, they are very welcome. Actually both features (public tesseract version and list of available languages) were already on my backlog for quite some time, I just never took the time to implement them.

The tests failed because they were still expecting `getTesseractVersion()` to be `protected`, but don't worry, I'll make the proper adjustments.

The only thing I'll pass are the doc comments, I used to have them in the past but decided to remove in favor of _hopefully_ self-explanatory function names.

As soon as I finish integrating your contributions (adding some tests and documentation on the README) I'll release a new version, to already make those new features available.

Thanks again 👍 🎉 🎈

**Comment by thiagoalessio** [comment]
Both features are available on version `2.7.0`.

**Comment by drsassafras** [comment]
Wow, thanks. I am integrating OCR support into www.tiki.org. As I am still in the process of integrating it, I won't hesitate to upstream some features here if I think a larger community could benefit from them.

The docblocks I have found to be handy for IDE integration. So no matter where I am I can always see what type is being returned or is expected. If errors are being thrown, along with any additional information that might be handy to a developer.

I am creating wrapper functions in Tiki so can just as easily include that functionality at that level. I am always happy to try to satisfy the coding style of each project I am working on.

**Comment by marclaporte** [comment]
Already available on https://packagist.org/packages/thiagoalessio/tesseract_ocr#2.7.0

Well done guys!

**Pull request merged**
